### ISSUE TITLE
VCS upload fails for larger repositories

### ISSUE THREAD

**Issue by djeverett** [fossology/fossology-python#36]
Seen in fossology-0.1.1:

I upload using this code:

```
root_folder = foss.list_folders()[0]
my_product_folder = foss.create_folder(root_folder, 'My_Product', 'My_Product')

vcs = {
    "vcsType": "git",
    "vcsName": "my-product-master",
    "vcsUrl": "https://gerrit-server/path/to/repo",
    "vcsUsername": "",
    "vcsPassword": "",
    "vcsBranch": "master"
}

my_product_upload = foss.upload_file(my_product_folder, vcs=vcs,
                                     access_level=AccessLevel.PUBLIC,
                                     description='My_Product source')
```

Now, this works for small repositories, but on larger ones (clone time > 3 mins), I get this failure:

```
Traceback (most recent call last):
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/tenacity/__init__.py", line 412, in call
    result = fn(*args, **kwargs)
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/fossology/uploads.py", line 41, in detail_upload
    raise TryAgain
tenacity.TryAgain

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "upload_scan.py", line 30, in <module>
    my_product_upload = foss.upload_file(my_product_folder, vcs=vcs,
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/fossology/uploads.py", line 162, in upload_file
    upload = self.detail_upload(response.json()["message"])
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/tenacity/__init__.py", line 329, in wrapped_f
    return self.call(f, *args, **kw)
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/tenacity/__init__.py", line 409, in call
    do = self.iter(retry_state=retry_state)
  File "/home/deverett/.virtualenvs/fossology/lib/python3.8/site-packages/tenacity/__init__.py", line 369, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f38d2aecbb0 state=finished raised TryAgain>]
```

**Comment by djeverett** [comment]
Note: the upload succeeds when done in the FOSSology web interface.

**Comment by deveaud-m** [comment]
@djeverett thanks for reporting this issue. The library will stop waiting for the unpack agent to finish shortly after 3 minutes. I guess the use-case you describe reaches this limit. I'll write a small patch to extend the upload waiting time to 5 minutes.

**Comment by deveaud-m** [comment]
@djeverett I just released a patch for this issue: https://pypi.org/project/fossology/0.1.2/, I hope this will help you.

**Comment by djeverett** [comment]
Thanks @deveaud-m for the rapid response.  I've just tested the fix and can confirm that it works for my use case.

**Comment by deveaud-m** [comment]
> Thanks @deveaud-m for the rapid response. I've just tested the fix and can confirm that it works for my use case.

Perfect! Thanks for the feedback :+1:
